northland/lp_trader/urls.py
from django.urls import path

from . import views

app_name = "lp_trader"
urlpatterns = [
    path("", views.index, name="index"),
    path("auth/login", views.login, name="login"),
    path("auth/update/warning", views.force_update_warning, name="update_warning"),
    path("auth/update/char", views.update_char, name="update_char"),
    path("auth/update/corp", views.update_corp, name="update_corp"),
    path("auth/update/item", views.update_item, name="update_item"),
    path("endpoints/get/loyalty", views.view_loyalty, name="view_loyalty"),
    path("endpoints/get/corp_wallet", views.view_corp_wallets, name="view_corp_wallet")
]

northland/northland/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'sso/', include('esi.urls', namespace='esi')),
    path('', include('lp_trader.urls'))
]

northland/lp_trader/models.py
from django.db import models
from django.utils import timezone

import datetime

# Create your models here.
class Corp(models.Model):
    """
    Django model for Corporation object. Toggle is_npc_corp option in code or Django admin
    page to differentiate
    """
    corp_name = models.CharField(max_length=300)
    corp_id = models.IntegerField()

    is_npc_corp = models.BooleanField(default=True)
    lp_exchange_rate = models.FloatField(default=0.8) # Determines how much corp LP can be obtained by exchanging x amount of CONCORD LP, requires manual input
    offers = models.JSONField()

    def __str__(self):
        return self.corp_name
    

class Character(models.Model):
    """
    Django model for Character object
    """
    char_name = models.CharField(max_length=300)
    char_id = models.IntegerField()
    wallet = models.JSONField()
    loyalty_points = models.JSONField()

    last_updated = models.DateTimeField("Last Updated")
    pull_data = models.BooleanField(default=True)

    def was_recently_updated(self) -> bool:
        """
        Checks if the model has been updated within the last hour
        
        Args:
            None
        
        Returns:
            bool: Model has been updated within the last hour
        """
        now = timezone.now()
        return now - datetime.timedelta(hours=1) <= self.last_updated <= now
    
    def __str__(self):
        return self.char_name
    
class Item(models.Model):
    """
    Django model for Item object
    """
    item_name = models.CharField(max_length=300)
    item_id = models.IntegerField()
    # JSON will contain Jita buy, split and sell values of item
    # e.g. 
    # plex = Item(item_name="PLEX", item_id="44992", market_price={"buy": 4500000, "split": 4750000, "sell": 5000000})
    market_price = models.JSONField() 

    last_updated = models.DateTimeField("Last Updated")
    pull_data = models.BooleanField(default=True)

    def was_recently_updated(self) -> bool:
        """
        Checks if the model has been updated within the last hour
        
        Args:
            None
        
        Returns:
            bool: Model has been updated within the last hour
        """
        now = timezone.now()
        return now - datetime.timedelta(hours=1) <= self.last_updated <= now
    
    def __str__(self):
        return self.item_name
    
class Blueprint(models.Model):
    """
    Django model for Blueprint object
    """
    item_name = models.CharField(max_length=300)
    item_id = models.IntegerField()

    baseME = models.IntegerField(default=0)
    baseTE = models.IntegerField(default=0)

    input_materials = models.JSONField()

    def __str__(self):
        return self.item_name

northland/lp_trader/views.py
from django.contrib import messages
from django.shortcuts import HttpResponse, HttpResponseRedirect, render
from django.urls import reverse
from esi.decorators import token_required
from esi.models import Token
from esi.managers import TokenQueryset

from .backend import data, endpoints
from .models import *
from northland.settings import ESI_SCOPES

# Create your views here.
def index(request):
    return render(request, "lp_trader/index.html")

@token_required(new=True, scopes=ESI_SCOPES)
def login(request, token):
    data.update_character_db(token)
    return HttpResponseRedirect(reverse("lp_trader:index"))


def force_update_warning(request):
    return render(request, "lp_trader/force_update.html")

def update_char(request):
    tokens = Token.objects.all()
    for token in tokens:
        data.update_character_db(token, force=True)
    return HttpResponseRedirect(reverse("lp_trader:index"))

def update_corp(request):
    corps = Corp.objects.all()
    for corp in corps:
        data.update_corp_loyalty_store(corp_id=corp.corp_id)
    return HttpResponseRedirect(reverse("lp_trader:index"))

def update_item(request):
    data.update_sde()
    return HttpResponseRedirect(reverse("lp_trader:index"))

def view_loyalty(request):
    data.check_for_character_update()
    characters = Character.objects.filter(pull_data=True)
    for character in characters:
        messages.success(request, f"{character.char_name}: {character.loyalty_points}")
    return HttpResponseRedirect(reverse("lp_trader:index"))

def view_corp_wallets(request):
    token = TokenQueryset(Token).require_scopes(["esi-wallet.read_corporation_wallets.v1", "esi-corporations.read_divisions.v1"])[0]
    balances = endpoints.get_corporation_wallet_balance(token)
    _, divisions = endpoints.get_corporation_divisions(token)
    remapped_wallets = {}
    for entry in balances:
        d, b = entry["division"], entry["balance"]
        div_name = divisions[d - 1]["name"]
        remapped_wallets["Master Wallet" if div_name is None else div_name] = b
    messages.success(request, remapped_wallets)
    return HttpResponseRedirect(reverse("lp_trader:index"))

northland/lp_trader/templates/lp_trader/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'lp_trader/style.css' %}">
</head>
<body>

<div class="navbar">
    <a href="{% url 'lp_trader:login' %}">Login</a>
    <div class="dropdown">
        <a href="#" class="dropbtn">View</a>
        <div class="dropdown-content">
            <a href="{% url 'lp_trader:view_loyalty' %}">View LP Quantities</a>
            <a href="{% url 'lp_trader:view_corp_wallet' %}">View Corp Wallet</a> 
        </div>
    </div>
    <div class="dropdown">
        <a href="#" class="dropbtn">Update</a>
        <div class="dropdown-content">
            <a href="{% url 'lp_trader:update_char' %}">Update Character DB</a>
            <a href="{% url 'lp_trader:update_corp' %}">Update Corp DB</a>
            <a href="{% url 'lp_trader:update_item' %}">Update Item DB</a> 
        </div>
    </div>
    <a href="{% url 'admin:index' %}">Admin</a>
</div>

{% block content %}{% endblock content%}

</body>
</html>

northland/lp_trader/templates/lp_trader/convert.html
{% extends 'lp_trader/base.html' %}

{% block content %}


{% endblock content %}

northland/lp_trader/templates/lp_trader/index.html
{% extends 'lp_trader/base.html' %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div> {{ message }}</div>
    {% endfor %}
</ul>
{% endif %}
{% endblock content %}